module.exports = {
	// plugins: ["prettier-plugin-tailwindcss"],
	printWidth: 80,
	semi: true,
	arrowParens: "always",
	bracketSpacing: true,
	endOfLine: "lf",
	htmlWhitespaceSensitivity: "css",
	insertPragma: false,
	singleAttributePerLine: false,
	bracketSameLine: false,
	jsxBracketSameLine: false,
	jsxSingleQuote: false,
	proseWrap: "preserve",
	quoteProps: "as-needed",
	requirePragma: false,
	singleQuote: false,
	tabWidth: 4,
	useTabs: true,
	trailingComma: "es5",
	embeddedLanguageFormatting: "auto",
	// indentStyle: "tab",
	// indentSize: 4,
	vueIndentScriptAndStyle: false,
	parser: "babel",
};
